_target_: robot_wm.modeling.networks.st_forward_model.STForwardModel
dim: 1536
num_heads: 24
num_layers: 18
x_dim: ???
context_dim: ???
output_dim: ???
rope_end: 1920
rope_theta: 50000
attn_drop_prob: 0.0
proj_drop_prob: 0.0
mlp_drop_prob: 0.0
residual_drop_prob: 0.0
use_video_cross_attention: True
