_target_: robot_wm.menagerie.dino_wm.DinoWM
config:
  model_ckpt_path: "/fsx-cortex/dud/dino_wm_robot/outputs/2025-03-21_21-01-25_5HZ_p209/0/checkpoints/model_latest.pth"
  model_cfg_path: "/fsx-cortex/dud/dino_wm_robot/outputs/2025-03-21_21-01-25_5HZ_p209/0/hydra.yaml"
  override_decoder: True
  decoder_ckpt_path: "/fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-02-28_23-31-35_large_2_scaled_vqvae_2x-BS_bigger-embs/0/checkpoints/model_latest.pth"
  decoder_cfg_path: "/fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-02-28_23-31-35_large_2_scaled_vqvae_2x-BS_bigger-embs/0/hydra.yaml"

  max_context: 9
  max_rollout_length: 100
  frame_skip: 5
  obs_frame_skip: 5
  use_amp: True
