_target_: robot_wm.menagerie.jepa_wm.JepaWM
config:
  size: 256
  window: 16
  tubulet_size: 2
  max_context: 20
  obs_frame_skip: 1
  wm_frequency: 7.5  # hz
  max_rollout_length: 1000
  grid_size: 16
  weight_path: "/fsx-cortex/shared/robotics-world-models/models/jepa-wm-rope"
