_target_: robot_wm.menagerie.mido_jepa_wm.JepaWM
config:
  size: 256
  window: 16
  tubulet_size: 2
  max_context: 20
  obs_frame_skip: 1
  wm_frequency: 7.5  # hz
  max_rollout_length: 1000
  grid_size: 16

  # from https://huggingface.co/facebook/robotics-world-models/blob/main/mido-jepa-wm-rope/franka-p0.yaml
  conditional_layer_norm: false
  resume_path: vitg16-vitlpred-proprio-noaug-leftcam-8fpc-4hz-2ar-latest.pth.tar
  decoder_path: mido_wm_decoder.pth.tar
  model_name: vit_giant_xformers
  normalize_reps: true
  pred_depth: 24
  pred_embed_dim: 1024
  pred_is_frame_causal: true
  pred_num_heads: 16
  uniform_power: true
  use_activation_checkpointing: true
  use_proprio: true
  old_pred: false
  use_rope: true
  # data
  crop_size: 256
  patch_size: 16
  fps: 30
  # more 
  use_extrinsics: False
  use_silu: False
  use_pred_silu: False
  wide_silu: True
  mpc: 
    rollout: 1
    samples: 500
    topk: 5
    cem_steps: 10
    momentum_mean: 0.15
    maxnorm: 0.2
    verbose: true