# @package _global_
defaults:
  - /datasets@libero_unseen_val_dataset: transformed_multi_libero
  - override /datasets@dataset: transformed_multi_libero
  - override /datasets@val_dataset: transformed_multi_libero
  - override /datasets@viz_dataset: transformed_multi_libero
  - override /models@model: latent_action_model_vq
  - override /tokenizers/rgb@model.rgb_tokenizer: cosmos
  - override /optimizers@optimizer_factory: adamw
  - override /lr_schedulers@lr_scheduler_factory: linear_warmup_cosine_decay
name: ???

dataset:  &dataset
  padding_dim: 0 #don't need to pad
  seed: ${seed}
  infinite: true
  transform:
      sample_size: 2
      chunk_size: 5
  datasets:
    Libero:  &libero
      seed: ${seed}
      manifest: "/svl/u/ravenh/lacwm/robot_world_models-raven-lam/robot_wm/datasets/csv_files/libero.csv"
      transform:
        action_type: action+camera+joint_states #26
        multiview: false
        sample_size: ${dataset.transform.sample_size}
        chunk_size: ${dataset.transform.chunk_size}



data_loader:
  batch_size: ???
  # num_workers: 0
  # pin_memory: true
  # persistent_workers: False
  # prefetch_factor: null

val_dataset:
  <<: *dataset
  datasets:
    Libero:
      <<: *libero
      manifest: "/svl/u/ravenh/lacwm/robot_world_models-raven-lam/robot_wm/datasets/csv_files/libero.csv"

libero_unseen_val_dataset:
  <<: *dataset
  datasets:
    Libero:
      <<: *libero
      manifest: "/svl/u/ravenh/lacwm/robot_world_models-raven-lam/robot_wm/datasets/csv_files/libero_val.csv"


val_data_loader:
  - _target_: torchdata.stateful_dataloader.StatefulDataLoader
    dataset: ${val_dataset}
    batch_size: ${data_loader.batch_size}
    num_workers: 2
    pin_memory: true
    prefetch_factor: 2
  - _target_: torchdata.stateful_dataloader.StatefulDataLoader
    dataset: ${libero_unseen_val_dataset}
    batch_size: ${data_loader.batch_size}
    num_workers: 2
    pin_memory: true
    prefetch_factor: 2


viz_data_loader:
  - _target_: torchdata.stateful_dataloader.StatefulDataLoader
    dataset: ${val_dataset}
    batch_size: 2
    num_workers: 2
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: False
  - _target_: torchdata.stateful_dataloader.StatefulDataLoader
    dataset: ${libero_unseen_val_dataset}
    batch_size: ${data_loader.batch_size}
    num_workers: 2
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: False


model:
  inverse_model:
    arch: ???
  rgb_tokenizer:
    tokenizer_name: Cosmos-0.1-Tokenizer-CI8x8
    output_dim: 16
  rgb_pos_embed:
    _args_:
      - ${dataset.transform.sample_size}
      - 32 #256/8
      - 32
  quantizer:
    _target_: robot_wm.modeling.modules.vector_quantization.VectorQuantizer
    dim: ???
    size: ???
  action_pos_embed:
    _args_:
      - ${dataset.transform.sample_size}
      - ${model.inverse_model.num_actions}
  forward_model:
    arch: ???
  action_decoder:
    _target_: robot_wm.modeling.modules.mlp.SplitMultiMLP
    input_dim: ${mul:${model.quantizer.dim},${model.inverse_model.num_actions}}
    split_type:
      action_type_split:
        "ee":
          - 0
          - ${div:${model.action_decoder.input_dim},2}
        'joint_states':
          - 0
          - ${div:${model.action_decoder.input_dim},2}
        "camera":
          - ${div:${model.action_decoder.input_dim},2}
          - ${model.action_decoder.input_dim}
      "5":
        "ee": 50
        'joint_states': 35
        "camera": 45
    decoders:
      "5": #robot
        # target: robot_wm.modeling.modules.mlp.MLP
        target: robot_wm.modeling.tokenizers.action.decoder.ActionXattenDecoder
        input_dim: ${model.action_decoder.input_dim}
        hidden_dim: 1024
        output_dim: 130

  loss_scheduler:
    pretrain_steps: ???
    warmup_steps: 10_000
    total_steps: ${trainer.config.max_iter}
    seed: ${seed}
  config:
    backprog_action_decoding: True
    action_decoding_weight: 100
    decode_zhat: False


optimizer_factory:
  lr: 3e-4
  betas: [0.9, 0.95]

lr_scheduler_factory:
  lr_lambda:
    warmup_steps: 6_000
    total_steps: ${trainer.config.max_iter}
    final_learning_rate: 3e-7

trainer:
  config:
    max_iter: 80_000
    gradient_clipping:
      max_norm: 0.75
