_target_: robot_wm.inference.actor.wm_mpc_planner.WMMPCPlanner
config:
  trajectory_optimization:
    _target_: robot_wm.inference.actor.planning.itmpc.ITMPC
    config:
      sample_size: 25
      iterations: 5
      pred_horizon_s: 1
      SIGMA: 0.045
      VIS_W: 1.0
      use_proprio: False
      PROP_W: 0.0
      cost:
        _target_: robot_wm.inference.actor.cost.visual_based_latents_cost.L2VisualLatentsCost

  world_model:
    _target_: robot_wm.menagerie.dino_wm.DinoWM
    config:
      # model_cfg_path: /fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-03-01_09-08-49_mid_1_3x_batchsize_bigger_embs/0/.hydra/config.yaml
      # model_ckpt_path: /fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-03-01_09-08-49_mid_1_3x_batchsize_bigger_embs/0/checkpoints/model_latest.pth
      model_cfg_path: /home/abhagejji/eai/robot_world_models/model_registry/dino/daniel/enq_DINOWM_5Hz_p209_nodec/hydra.yaml
      model_ckpt_path: /home/abhagejji/eai/robot_world_models/model_registry/dino/daniel/enq_DINOWM_5Hz_p209_nodec/model_latest.pth
      max_context: 1
      max_rollout_length: 100
      use_amp: True
      obs_frame_skip: 1
      frame_skip: 5

  robot_frequency: 30   # hz
  actor_frequency: 5    # hz
  planning_frequency: 1 # hz

  plan_every: 0
  action_aggregation_horizon: 1
  max_history_size: 900
