_target_: robot_wm.inference.actor.wm_mpc_planner.WMMPCPlanner
config:
  trajectory_optimization:
    _target_: robot_wm.inference.actor.planning.itmpc.ITMPC
    config:
      sample_size: 50
      iterations: 10
      pred_horizon_s: 1
      SIGMA: 0.04
      cost:
        _target_: robot_wm.inference.actor.cost.visual_based_latents_cost.L2VisualLatentsCost


  world_model:
    _target_: robot_wm.menagerie.dino_wm.DinoWM
    config:
      model_ckpt_path: "/home/abhagejji/eai/robot_world_models/model_registry/dino/daniel/enq_DINOWM_5Hz_p209_nodec/model_latest.pth"
      model_cfg_path: "/home/abhagejji/eai/robot_world_models/model_registry/dino/daniel/enq_DINOWM_5Hz_p209_nodec/hydra.yaml"
      override_decoder: True
      # decoder_ckpt_path: "/fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-02-28_23-31-35_large_2_scaled_vqvae_2x-BS_bigger-embs/0/checkpoints/model_latest.pth"
      # decoder_cfg_path: "/fsx-cortex/sergioarnaud/dino_wm_robot/outputs/2025-02-28_23-31-35_large_2_scaled_vqvae_2x-BS_bigger-embs/0/hydra.yaml"

      decoder_cfg_path: "/home/abhagejji/Code/franka_deoxys_ros/model_registry/dino_wm/sergio_latest/config.yaml"
      decoder_ckpt_path: "/home/abhagejji/Code/franka_deoxys_ros/model_registry/dino_wm/sergio_latest/epoch_1.pth"

      max_context: 1
      max_rollout_length: 100
      use_amp: True
      obs_frame_skip: 1
      frame_skip: 5

  robot_frequency: 30   # hz
  actor_frequency: 5    # hz
  planning_frequency: 1 # hz

  plan_every: 0
  action_aggregation_horizon: 1
  max_history_size: 900
