# @package _global_
defaults:
  - /experiments_0908/action_variation_common
  - _self_

name: action-variation-av-cont-seed1234-u000200
model:
  action_variation:
    enabled: false
wandb:
  tags: [abc, vpm, action-variation, control, seed-1234]
