_target_: robot_wm.datasets.droid.dataset.DroidDataset
manifest: ???
seed: ???
infinite: ${infinite}
random_mask_camera: 0
transform:
  _target_: robot_wm.datasets.droid.transform.DroidTransform
  cameras: ["exterior_image_1_left", "exterior_image_2_left"]
  output_keys: ["rgb", "actions", "mask"]
  sample_size: ???
  chunk_size: ???
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  resize_to: [180, 320]
  random_crop: null
  random_stretch: null
  action_type: delta-state
  integrate_chunks: false
  seed: ${seed}
  multiview: false
  try_to_order_cameras: false
to_numpy: false
normalize_keys: ["actions"]
