_target_: robot_wm.datasets.multi_dataset.MultiDataset
padding_dim: ???
seed: ???
infinite: true
transform:
  sample_size: ???
  chunk_size: ???
datasets:
  Droid:
    _target_: robot_wm.datasets.droid.lerobot_dataset.DroidLeRobotDataset
    data_dir: /scr/ravenh/lacwm_data/droid_lerobot
    seed: ???
    infinite: ${infinite}
    transform:
      _target_: robot_wm.datasets.droid.transform.DroidTransform
      cameras: ["exterior_image_1_left", "exterior_image_2_left"]
      output_keys: ["rgb", "actions", "mask"]
      sample_size: ???
      chunk_size: ???
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      action_type: delta-state+camera+abs_finger
      integrate_chunks: false
      seed: ${seed}
      multiview: false
    normalize_keys: null
