#!/usr/bin/env python3
"""Capture and preflight the isolated MuJoCo cache-rendering runtime.

The cache renderer intentionally uses a small, cache-only virtual environment.
Its ``bin/python`` is a symlink to the shared CPython binary; invoking the
resolved target would discard the cache virtual environment and therefore its
MuJoCo installation.  This helper records the lexical entry point and complete
symlink chain before importing the pinned packages and allocating an EGL
renderer.
"""

from __future__ import annotations

import argparse
import base64
import binascii
import csv
import hashlib
import importlib
import importlib.metadata
import json
import os
import platform
import site
import stat
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any


SCHEMA_VERSION = 1
RUNTIME_KIND = "raw_physics_flow_cache_renderer_runtime_v1"
EXPECTED_DISTRIBUTIONS = {
    "lz4": "4.4.5",
    "mcap": "1.4.0",
    "mcap-protobuf-support": "0.5.4",
    "mujoco": "3.3.7",
    "numpy": "2.0.1",
    "protobuf": "7.35.1",
    "zstandard": "0.25.0",
}
EXPECTED_IMPORT_NAMES = {
    "lz4": "lz4",
    "mcap": "mcap",
    "mcap-protobuf-support": "mcap_protobuf",
    "mujoco": "mujoco",
    "numpy": "numpy",
    "protobuf": "google.protobuf",
    "zstandard": "zstandard",
}
EXPECTED_AMBIGUOUS_RECORD_ENTRIES = {
    "lz4": [],
    "mcap": [],
    "mcap-protobuf-support": [],
    "mujoco": [],
    # NumPy's installed RECORD declares this generated bytecode path twice:
    # once unhashed and once with an obsolete wheel-build hash. Its observed
    # bytes are sealed below; unique hash declarations may never mismatch.
    "numpy": [
        {
            "path": "numpy/distutils/__pycache__/conv_template.cpython-310.pyc",
            "bytes": 8376,
            "sha256": (
                "2f442d2a269b70f5dfaf68e0f6355a00c27c24ccbd5f89c76654546fb87c72d9"
            ),
            "declared_sha256": (
                "8157884e9c3f1fff1bbe2884fdb7073b83abaa796a1c6e2e19b63022f9e597a9"
            ),
            "declared_bytes": 8270,
            "duplicate_unhashed_declaration": True,
        }
    ],
    "protobuf": [],
    "zstandard": [],
}
EXPECTED_RECORD_INVENTORIES = {
    "lz4": {
        "declared_entry_count": 17,
        "declared_unique_path_count": 17,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 12,
        "sha256_declared_total_bytes": 5_829_481,
        "sha256_inventory_identity_sha256": (
            "6e331b146883b550c040c0ed6fb8bb7039300acf9fa3bf286d6ffcf8da80f0a6"
        ),
        "unhashed_entry_count": 5,
        "unhashed_existing_file_count": 5,
        "unhashed_inventory_identity_sha256": (
            "2b8449d0528853c328c31fc88243f17accbd7e2729271415f632f1705f9c05a9"
        ),
        "native_library_count": 3,
        "native_library_total_bytes": 5_791_376,
        "native_library_inventory_identity_sha256": (
            "32712fe2a604a0c624a5fbb1900b8a74343f0be00966b708a6c56ad3f7b0f441"
        ),
    },
    "mcap": {
        "declared_entry_count": 35,
        "declared_unique_path_count": 35,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 20,
        "sha256_declared_total_bytes": 79_980,
        "sha256_inventory_identity_sha256": (
            "124338c71e4e942c6a7af2ee88ddf7552ffa3da3464934e38bcc65777796b2d7"
        ),
        "unhashed_entry_count": 15,
        "unhashed_existing_file_count": 15,
        "unhashed_inventory_identity_sha256": (
            "d9b695232a62df3ca38dce0131b47a3e856e6ee5a26484d9f9689028a60194ea"
        ),
        "native_library_count": 0,
        "native_library_total_bytes": 0,
        "native_library_inventory_identity_sha256": (
            "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"
        ),
    },
    "mujoco": {
        "declared_entry_count": 149,
        "declared_unique_path_count": 149,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 102,
        "sha256_declared_total_bytes": 21_118_024,
        "sha256_inventory_identity_sha256": (
            "55defb74c6318fe03fd9a4c791213d73d8915bdfa00760ff87dc788fad43372b"
        ),
        "unhashed_entry_count": 47,
        "unhashed_existing_file_count": 47,
        "unhashed_inventory_identity_sha256": (
            "8d4581aa5d05da05aae926bdc81ab3790648bdb566d66d977425592eeadcffdb"
        ),
        "native_library_count": 15,
        "native_library_total_bytes": 19_092_432,
        "native_library_inventory_identity_sha256": (
            "23340861981d01decc6cd3b6e3ef14cc5ba78a918911a48d9eb8283908f7b2a6"
        ),
    },
    "mcap-protobuf-support": {
        "declared_entry_count": 17,
        "declared_unique_path_count": 17,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 11,
        "sha256_declared_total_bytes": 15_442,
        "sha256_inventory_identity_sha256": (
            "d050822c66d39fabaed5365b3f9c7df2bf4adb19fbfe7db0bd5ccfa1c912b2bb"
        ),
        "unhashed_entry_count": 6,
        "unhashed_existing_file_count": 6,
        "unhashed_inventory_identity_sha256": (
            "ccb633d7097678e05a47b01b2e9ed62401a33e5dda770b2fccf321ae07ffb1b4"
        ),
        "native_library_count": 0,
        "native_library_total_bytes": 0,
        "native_library_inventory_identity_sha256": (
            "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"
        ),
    },
    "numpy": {
        "declared_entry_count": 1_415,
        "declared_unique_path_count": 1_414,
        "duplicate_entry_count": 1,
        "sha256_declared_file_count": 933,
        "sha256_declared_total_bytes": 69_835_210,
        "sha256_inventory_identity_sha256": (
            "b2726d5be7c706c576ed18dd446bd5e718e8cf1626492caa85ed04a2dacf7882"
        ),
        "unhashed_entry_count": 480,
        "unhashed_existing_file_count": 480,
        "unhashed_inventory_identity_sha256": (
            "9853fd4e7ffe595821595f0a104f919821c48cb4590b32af00a44d30332260db"
        ),
        "native_library_count": 22,
        "native_library_total_bytes": 57_850_758,
        "native_library_inventory_identity_sha256": (
            "d16b90eff1467ef06aa1361962619d1c1ca09d7d8ba96c19ee47da68e8478300"
        ),
    },
    "protobuf": {
        "declared_entry_count": 114,
        "declared_unique_path_count": 114,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 59,
        "sha256_declared_total_bytes": 1_327_345,
        "sha256_inventory_identity_sha256": (
            "38b9a6f09a7de3233d7803c2aabff9bc532c4b9fec8b4ae6bd87f14e60128cfc"
        ),
        "unhashed_entry_count": 55,
        "unhashed_existing_file_count": 55,
        "unhashed_inventory_identity_sha256": (
            "6e8c5e73153f0ebe74c9b118e82db9f326ce8adbd91f1e0ef1639961f13a8715"
        ),
        "native_library_count": 1,
        "native_library_total_bytes": 406_232,
        "native_library_inventory_identity_sha256": (
            "87934fe7846a9a78d29b7e7243f8cbc5311a4797d0fd39e145bf7a30fe44fa51"
        ),
    },
    "zstandard": {
        "declared_entry_count": 14,
        "declared_unique_path_count": 14,
        "duplicate_entry_count": 0,
        "sha256_declared_file_count": 11,
        "sha256_declared_total_bytes": 23_918_271,
        "sha256_inventory_identity_sha256": (
            "9fb7fc2c56df12edeb480987133fc80ccdd37a5724da4df7a7a9db318cc005b0"
        ),
        "unhashed_entry_count": 3,
        "unhashed_existing_file_count": 3,
        "unhashed_inventory_identity_sha256": (
            "f30a7baed0878a931da86c0fe392263937fb68837249a6e166ad51021958638d"
        ),
        "native_library_count": 2,
        "native_library_total_bytes": 23_739_512,
        "native_library_inventory_identity_sha256": (
            "f895aaff25b70ccc4ebf684a0da5c5d62c3004fc4a640c30cf880bfbedc5c27f"
        ),
    },
}
PREFLIGHT_HEIGHT = 8
PREFLIGHT_WIDTH = 8
PREFLIGHT_XML = """
<mujoco model="physics_flow_cache_runtime_preflight">
  <visual><global offwidth="8" offheight="8"/></visual>
  <worldbody>
    <light pos="0 0 2"/>
    <camera name="preflight" pos="0 0 2"/>
    <geom type="box" size="0.2 0.2 0.2" rgba="0.8 0.2 0.1 1"/>
  </worldbody>
</mujoco>
"""


class CacheRuntimeError(RuntimeError):
    """The cache-only interpreter or renderer does not match its contract."""


def canonical_json(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def identity_payload(payload: Mapping[str, Any]) -> dict[str, Any]:
    unsigned = dict(payload)
    unsigned.pop("identity_sha256", None)
    return {
        **unsigned,
        "identity_sha256": hashlib.sha256(canonical_json(unsigned)).hexdigest(),
    }


def sha256_file(path: Path, block_bytes: int = 16 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while block := handle.read(block_bytes):
            digest.update(block)
    return digest.hexdigest()


def regular_file_record(path: Path) -> dict[str, Any]:
    if not path.is_absolute() or not path.is_file() or path.is_symlink():
        raise CacheRuntimeError(f"absolute regular file required: {path}")
    canonical = path.resolve(strict=True)
    return {
        "path": str(canonical),
        "bytes": canonical.stat().st_size,
        "sha256": sha256_file(canonical),
    }


def _is_native_library(path: Path) -> bool:
    name = path.name.lower()
    return (
        ".so" in name
        or name.endswith(".dylib")
        or name.endswith(".dll")
        or name.endswith(".pyd")
    )


def verify_distribution_record(record_path: Path, prefix: Path) -> dict[str, Any]:
    """Verify unambiguous RECORD hashes and bind every other declared entry.

    Wheel ``RECORD`` paths are relative to site-packages and may legitimately
    reach the venv's ``bin`` directory (for example NumPy's ``f2py``).  They
    may never escape the registered virtual-environment prefix.
    """

    record_path = record_path.resolve(strict=True)
    prefix = prefix.resolve(strict=True)
    site_packages = record_path.parent.parent
    verified: list[dict[str, Any]] = []
    unhashed: list[dict[str, Any]] = []
    native: list[dict[str, Any]] = []
    try:
        with record_path.open(newline="", encoding="utf-8") as handle:
            rows = list(csv.reader(handle))
    except (OSError, UnicodeError, csv.Error) as exc:
        raise CacheRuntimeError(f"invalid distribution RECORD: {record_path}") from exc
    if not rows:
        raise CacheRuntimeError(f"empty distribution RECORD: {record_path}")
    entries: dict[str, list[tuple[str, str, int]]] = {}
    for row_number, row in enumerate(rows, start=1):
        if len(row) != 3 or not row[0]:
            raise CacheRuntimeError(
                f"invalid distribution RECORD row {record_path}:{row_number}"
            )
        relative, declared_hash, declared_size = row
        entries.setdefault(relative, []).append(
            (declared_hash, declared_size, row_number)
        )
    ambiguous: list[dict[str, Any]] = []
    for relative in sorted(entries):
        declarations = entries[relative]
        hashed = [value for value in declarations if value[0]]
        unhashed_declaration = any(not value[0] for value in declarations)
        if len({value[:2] for value in hashed}) > 1:
            raise CacheRuntimeError(
                f"conflicting duplicate distribution RECORD entry: {relative}"
            )
        declared_hash, declared_size, row_number = (
            hashed[0] if hashed else declarations[0]
        )
        relative_path = Path(relative)
        if relative_path.is_absolute():
            raise CacheRuntimeError(
                f"absolute distribution RECORD entry: {record_path}:{row_number}"
            )
        lexical = site_packages / relative_path
        try:
            resolved = lexical.resolve(strict=True)
        except OSError:
            if hashed:
                raise CacheRuntimeError(
                    f"hashed distribution file is missing: {relative}"
                )
            unhashed.append({"path": relative, "present": False})
            continue
        if prefix != resolved and prefix not in resolved.parents:
            raise CacheRuntimeError(f"distribution file escapes venv: {relative}")
        if not lexical.is_file() or lexical.is_symlink():
            raise CacheRuntimeError(f"distribution entry is not a regular file: {relative}")
        size = resolved.stat().st_size
        digest = sha256_file(resolved)
        observed = {"path": relative, "bytes": size, "sha256": digest}
        if hashed:
            try:
                algorithm, encoded = declared_hash.split("=", 1)
                expected = base64.urlsafe_b64decode(
                    encoded + "=" * (-len(encoded) % 4)
                ).hex()
            except (ValueError, binascii.Error) as exc:
                raise CacheRuntimeError(
                    f"invalid distribution hash: {record_path}:{row_number}"
                ) from exc
            if algorithm != "sha256" or len(expected) != 64:
                raise CacheRuntimeError(f"distribution hash is unsupported: {relative}")
            declared_size_valid = declared_size.isdigit()
            hash_matches = expected == digest
            size_matches = declared_size_valid and int(declared_size) == size
            if hash_matches and size_matches:
                verified.append(observed)
                if _is_native_library(relative_path):
                    native.append(observed)
            elif (
                unhashed_declaration
                and relative_path.suffix == ".pyc"
                and not _is_native_library(relative_path)
            ):
                # A path that RECORD itself also declares unhashed is
                # intrinsically ambiguous. Bind both declarations and the
                # observed bytes rather than silently calling the stale hash
                # verified. The exact allowed anomaly path is package-pinned.
                ambiguous.append(
                    {
                        **observed,
                        "declared_sha256": expected,
                        "declared_bytes": (
                            int(declared_size) if declared_size_valid else None
                        ),
                        "duplicate_unhashed_declaration": True,
                    }
                )
            else:
                raise CacheRuntimeError(f"distribution hash differs: {relative}")
        else:
            unhashed.append({**observed, "present": True})
    if not verified:
        raise CacheRuntimeError(f"distribution RECORD has no verified files: {record_path}")
    return {
        "declared_entry_count": len(rows),
        "declared_unique_path_count": len(entries),
        "duplicate_entry_count": len(rows) - len(entries),
        "sha256_declared_file_count": len(verified),
        "sha256_declared_total_bytes": sum(row["bytes"] for row in verified),
        "sha256_inventory_identity_sha256": hashlib.sha256(
            canonical_json(verified)
        ).hexdigest(),
        "unhashed_entry_count": len(unhashed),
        "unhashed_existing_file_count": sum(
            row["present"] is True for row in unhashed
        ),
        "unhashed_inventory_identity_sha256": hashlib.sha256(
            canonical_json(unhashed)
        ).hexdigest(),
        "ambiguous_duplicate_paths": [row["path"] for row in ambiguous],
        "ambiguous_duplicate_entries": ambiguous,
        "ambiguous_duplicate_entry_count": len(ambiguous),
        "ambiguous_duplicate_inventory_identity_sha256": hashlib.sha256(
            canonical_json(ambiguous)
        ).hexdigest(),
        "native_library_count": len(native),
        "native_library_total_bytes": sum(row["bytes"] for row in native),
        "native_library_inventory_identity_sha256": hashlib.sha256(
            canonical_json(native)
        ).hexdigest(),
        "all_unambiguous_declared_sha256_entries_verified": True,
    }


def lexical_absolute(path: Path) -> Path:
    """Make a path absolute without resolving its final or parent symlinks."""

    expanded = path.expanduser()
    if not expanded.is_absolute():
        raise CacheRuntimeError(f"absolute Python entry point required: {path}")
    return Path(os.path.abspath(os.fspath(expanded)))


def python_entry_identity(entry: Path) -> dict[str, Any]:
    """Bind the lexical venv entry, every link target, and final executable."""

    entry = lexical_absolute(entry)
    current = entry
    chain: list[dict[str, str]] = []
    visited: set[str] = set()
    for _ in range(16):
        key = str(current)
        if key in visited:
            raise CacheRuntimeError("Python entry point contains a symlink cycle")
        visited.add(key)
        try:
            mode = current.lstat().st_mode
        except OSError as exc:
            raise CacheRuntimeError(f"Python entry point is unavailable: {current}") from exc
        if not stat.S_ISLNK(mode):
            break
        target = os.readlink(current)
        chain.append({"path": str(current), "link_target": target})
        candidate = Path(target)
        if not candidate.is_absolute():
            candidate = current.parent / candidate
        current = Path(os.path.abspath(os.fspath(candidate)))
    else:
        raise CacheRuntimeError("Python entry point symlink chain is too deep")
    if not chain:
        raise CacheRuntimeError(
            "cache Python must be invoked through its virtual-environment symlink"
        )
    if not current.is_file() or current.is_symlink() or not os.access(current, os.X_OK):
        raise CacheRuntimeError(f"resolved Python executable is invalid: {current}")
    return {
        "entry_path": str(entry),
        "entry_is_symlink": True,
        "symlink_chain": chain,
        "resolved_executable": regular_file_record(current),
    }


def _distribution_record(distribution: importlib.metadata.Distribution) -> Path:
    candidates = [
        Path(distribution.locate_file(relative))
        for relative in (distribution.files or ())
        if relative.name == "RECORD" and ".dist-info" in str(relative.parent)
    ]
    if len(candidates) != 1:
        raise CacheRuntimeError(
            f"expected one RECORD for {distribution.metadata.get('Name', 'package')}"
        )
    return candidates[0]


def _package_identity(name: str, expected_version: str, prefix: Path) -> dict[str, Any]:
    import_name = EXPECTED_IMPORT_NAMES[name]
    try:
        module = importlib.import_module(import_name)
        distribution = importlib.metadata.distribution(name)
        version = importlib.metadata.version(name)
    except (ImportError, importlib.metadata.PackageNotFoundError) as exc:
        raise CacheRuntimeError(f"required cache package is unavailable: {name}") from exc
    if version != expected_version:
        raise CacheRuntimeError(
            f"{name} version differs: observed={version!r} expected={expected_version!r}"
        )
    module_path = Path(str(getattr(module, "__file__", ""))).resolve(strict=True)
    record_path = _distribution_record(distribution).resolve(strict=True)
    prefix = prefix.resolve(strict=True)
    if prefix not in module_path.parents or prefix not in record_path.parents:
        raise CacheRuntimeError(f"{name} did not import from the cache virtual environment")
    verified_record = verify_distribution_record(record_path, prefix)
    if (
        verified_record["ambiguous_duplicate_entries"]
        != EXPECTED_AMBIGUOUS_RECORD_ENTRIES[name]
    ):
        raise CacheRuntimeError(f"{name} RECORD ambiguity inventory differs")
    if any(
        verified_record.get(key) != expected
        for key, expected in EXPECTED_RECORD_INVENTORIES[name].items()
    ):
        raise CacheRuntimeError(f"{name} installed RECORD inventory differs")
    if name in {"mujoco", "numpy"} and verified_record["native_library_count"] < 1:
        raise CacheRuntimeError(f"{name} RECORD contains no verified native library")
    return {
        "distribution": name,
        "import_name": import_name,
        "version": version,
        "module": regular_file_record(module_path),
        "distribution_record": regular_file_record(record_path),
        "verified_record_inventory": verified_record,
    }


def _renderer_preflight(mujoco: Any) -> dict[str, Any]:
    if os.environ.get("MUJOCO_GL") != "egl":
        raise CacheRuntimeError("MUJOCO_GL must equal 'egl' for cache rendering")
    renderer = None
    try:
        model = mujoco.MjModel.from_xml_string(PREFLIGHT_XML)
        data = mujoco.MjData(model)
        mujoco.mj_forward(model, data)
        renderer = mujoco.Renderer(
            model,
            height=PREFLIGHT_HEIGHT,
            width=PREFLIGHT_WIDTH,
        )
        renderer.update_scene(data, camera="preflight")
        image = renderer.render()
        shape = [int(value) for value in image.shape]
        dtype = str(image.dtype)
        if shape != [PREFLIGHT_HEIGHT, PREFLIGHT_WIDTH, 3] or dtype != "uint8":
            raise CacheRuntimeError(
                f"MuJoCo renderer output differs: shape={shape} dtype={dtype}"
            )
    except CacheRuntimeError:
        raise
    except Exception as exc:
        raise CacheRuntimeError("MuJoCo EGL renderer preflight failed") from exc
    finally:
        if renderer is not None:
            renderer.close()
    return {
        "passed": True,
        "headless_backend": "egl",
        "render_shape": [PREFLIGHT_HEIGHT, PREFLIGHT_WIDTH, 3],
        "render_dtype": "uint8",
        "mujoco_library_version": str(mujoco.mj_versionString()),
    }


def _calibration_preflight(
    raw_mcap: Path,
    expected_identity_sha256: str,
) -> dict[str, Any]:
    raw_mcap = raw_mcap.expanduser()
    if (
        not raw_mcap.is_absolute()
        or not raw_mcap.is_file()
        or raw_mcap.is_symlink()
    ):
        raise CacheRuntimeError("registered calibration MCAP is unavailable")
    raw_mcap = raw_mcap.resolve(strict=True)
    if (
        len(expected_identity_sha256) != 64
        or any(value not in "0123456789abcdef" for value in expected_identity_sha256)
    ):
        raise CacheRuntimeError("registered calibration identity is invalid")
    repository = Path(__file__).resolve().parents[1]
    if str(repository) not in sys.path:
        sys.path.insert(0, str(repository))
    try:
        from tools.abc_d405_nominal_geometry_probe import (
            CAMERA_TYPE,
            _decode_top_calibration,
        )

        before = raw_mcap.stat()
        calibration = _decode_top_calibration(raw_mcap)
        after = raw_mcap.stat()
    except Exception as exc:
        raise CacheRuntimeError("registered D405 calibration decode failed") from exc
    observed_identity = hashlib.sha256(canonical_json(calibration)).hexdigest()
    if (
        before.st_size != after.st_size
        or before.st_mtime_ns != after.st_mtime_ns
        or observed_identity != expected_identity_sha256
        or calibration.get("camera_type") != CAMERA_TYPE
        or calibration.get("camera_width") != 640
        or calibration.get("camera_height") != 480
        or len(calibration.get("K", [])) != 9
        or not {"/top-camera", "/top-camera-info"}.issubset(
            calibration.get("topics", [])
        )
    ):
        raise CacheRuntimeError("registered D405 calibration preflight differs")
    return {
        "passed": True,
        "raw_mcap": {
            "path": str(raw_mcap),
            "bytes": after.st_size,
            "mtime_ns": after.st_mtime_ns,
            "device": after.st_dev,
            "inode": after.st_ino,
            "content_digest_computed": False,
        },
        "calibration_identity_sha256": observed_identity,
        "camera_type": CAMERA_TYPE,
        "camera_width": int(calibration["camera_width"]),
        "camera_height": int(calibration["camera_height"]),
        "intrinsic_count": len(calibration["K"]),
        "topics": calibration["topics"],
        "registered_d405_calibration_decoded": True,
        "future_rgb_message_decoded": False,
        "protected_test_accessed": False,
    }


def collect_runtime_receipt(
    python_entry: Path,
    calibration_mcap: Path,
    expected_calibration_identity_sha256: str,
) -> dict[str, Any]:
    """Capture the current process; never follow ``python_entry`` to execute it."""

    entry = lexical_absolute(python_entry)
    observed_executable = lexical_absolute(Path(sys.executable))
    if observed_executable != entry:
        raise CacheRuntimeError(
            "cache runtime must execute the registered symlink itself: "
            f"observed={observed_executable} registered={entry}"
        )
    prefix = Path(sys.prefix)
    expected_prefix = entry.parent.parent
    if prefix != expected_prefix:
        raise CacheRuntimeError(
            f"cache virtual-environment prefix differs: {prefix} != {expected_prefix}"
        )
    if sys.flags.no_user_site != 1 or site.ENABLE_USER_SITE is not False:
        raise CacheRuntimeError("cache runtime requires PYTHONNOUSERSITE=1")
    user_site = Path(site.getusersitepackages())
    if any(Path(value) == user_site for value in sys.path if value):
        raise CacheRuntimeError("user site-packages leaked into the cache runtime")
    entry_identity = python_entry_identity(entry)
    pyvenv = entry.parent.parent / "pyvenv.cfg"
    packages = {
        name: _package_identity(name, version, prefix)
        for name, version in EXPECTED_DISTRIBUTIONS.items()
    }
    mujoco = importlib.import_module("mujoco")
    return identity_payload(
        {
            "schema_version": SCHEMA_VERSION,
            "kind": RUNTIME_KIND,
            "python_entry": entry_identity,
            "pyvenv_cfg": regular_file_record(pyvenv),
            "python": {
                "sys_executable": sys.executable,
                "sys_prefix": sys.prefix,
                "sys_base_prefix": sys.base_prefix,
                "version": sys.version,
                "platform": platform.platform(),
                "no_user_site": True,
            },
            "packages": packages,
            "renderer_preflight": _renderer_preflight(mujoco),
            "calibration_preflight": _calibration_preflight(
                calibration_mcap,
                expected_calibration_identity_sha256,
            ),
            "helper_source": regular_file_record(Path(__file__)),
            "protected_test_accessed": False,
        }
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--python-entry", type=Path, required=True)
    parser.add_argument("--calibration-mcap", type=Path, required=True)
    parser.add_argument(
        "--expected-calibration-identity-sha256",
        required=True,
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    receipt = collect_runtime_receipt(
        args.python_entry,
        args.calibration_mcap,
        args.expected_calibration_identity_sha256,
    )
    print(canonical_json(receipt).decode("utf-8"), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
