defaults:
  - _self_
  - /tokenizers/rgb@rgb_tokenizer: ???
  - /modules@rgb_pos_embed: positional_embedding
  - /networks@inverse_model: st_inverse_model
  - /modules@action_pos_embed: positional_embedding
  - /networks@forward_model: st_forward_model

_target_: lam.latent_action_model.LatentActionModel
rgb_tokenizer: ${rgb_tokenizer}
rgb_pos_embed:
  _args_: ???
  dim: ${..rgb_tokenizer.output_dim}
inverse_model:
  arch: ???
  num_actions: 1
  input_dim: ${..rgb_tokenizer.output_dim}
  output_dim: 4  # len(quantizer.levels)
quantizer:
  _target_: robot_wm.modeling.modules.finite_scalar_quantization.FSQ
  levels: ???
action_pos_embed:
  _args_: ???
  dim: 4  # len(quantizer.levels)
action_decoder:
forward_model:
  arch: ???
  x_dim: ${..rgb_tokenizer.output_dim}
  context_dim: 4  # len(quantizer.levels)
  output_dim: ${.x_dim}
